
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox4;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox8;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label label8;

	private global::Gtk.ComboBox reflectorType;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label41;

	private global::Gtk.ComboBox reflectorPosition;

	private global::Gtk.Label GtkLabel;

	private global::Gtk.Frame frame4;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label13;

	private global::Gtk.ComboBox rotorLeftType;

	private global::Gtk.ComboBox rotorCenterType;

	private global::Gtk.ComboBox rotorRightType;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Label label14;

	private global::Gtk.ComboBox rotorLeftPosotion;

	private global::Gtk.ComboBox rotorCenterPosition;

	private global::Gtk.ComboBox rotorRightPosition;

	private global::Gtk.Label GtkLabel1;

	private global::Gtk.Frame plugboard1;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.Table plugboard_table;

	private global::Gtk.ComboBox A;

	private global::Gtk.ComboBox B;

	private global::Gtk.ComboBox C;

	private global::Gtk.ComboBox D;

	private global::Gtk.ComboBox E;

	private global::Gtk.ComboBox F;

	private global::Gtk.ComboBox G;

	private global::Gtk.ComboBox H;

	private global::Gtk.ComboBox I;

	private global::Gtk.ComboBox J;

	private global::Gtk.ComboBox K;

	private global::Gtk.ComboBox L;

	private global::Gtk.Label label15;

	private global::Gtk.Label label16;

	private global::Gtk.Label label17;

	private global::Gtk.Label label18;

	private global::Gtk.Label label19;

	private global::Gtk.Label label20;

	private global::Gtk.Label label21;

	private global::Gtk.Label label22;

	private global::Gtk.Label label23;

	private global::Gtk.Label label24;

	private global::Gtk.Label label25;

	private global::Gtk.Label label26;

	private global::Gtk.Label label27;

	private global::Gtk.Label label28;

	private global::Gtk.Label label29;

	private global::Gtk.Label label30;

	private global::Gtk.Label label31;

	private global::Gtk.Label label32;

	private global::Gtk.Label label33;

	private global::Gtk.Label label34;

	private global::Gtk.Label label35;

	private global::Gtk.Label label36;

	private global::Gtk.Label label37;

	private global::Gtk.Label label38;

	private global::Gtk.Label label39;

	private global::Gtk.Label label40;

	private global::Gtk.ComboBox M;

	private global::Gtk.ComboBox N;

	private global::Gtk.ComboBox O;

	private global::Gtk.ComboBox P;

	private global::Gtk.ComboBox Q;

	private global::Gtk.ComboBox R;

	private global::Gtk.ComboBox S;

	private global::Gtk.ComboBox T;

	private global::Gtk.ComboBox U;

	private global::Gtk.ComboBox V;

	private global::Gtk.ComboBox W;

	private global::Gtk.ComboBox X;

	private global::Gtk.ComboBox Y;

	private global::Gtk.ComboBox Z;

	private global::Gtk.Label GtkLabel2;

	private global::Gtk.Frame frame8;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox11;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView inputText;

	private global::Gtk.ScrolledWindow decryptedMessage;

	private global::Gtk.TextView outputText;

	private global::Gtk.Button button3;

	private global::Gtk.Label GtkLabel4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "Enigma Emulator";
		this.Title = global::Mono.Unix.Catalog.GetString("Enigma Emulator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.WidthRequest = 80;
		this.label8.Name = "label8";
		this.label8.Xalign = 0F;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Type");
		this.hbox6.Add(this.label8);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label8]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.reflectorType = global::Gtk.ComboBox.NewText();
		this.reflectorType.AppendText(global::Mono.Unix.Catalog.GetString("-B-"));
		this.reflectorType.AppendText(global::Mono.Unix.Catalog.GetString("-C-"));
		this.reflectorType.Name = "combobox8";
		this.reflectorType.Active = 0;
		this.hbox6.Add(this.reflectorType);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.reflectorType]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox8.Add(this.hbox6);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox6]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label41 = new global::Gtk.Label();
		this.label41.WidthRequest = 80;
		this.label41.Name = "label41";
		this.label41.Xalign = 0F;
		this.label41.LabelProp = global::Mono.Unix.Catalog.GetString("Position");
		this.hbox7.Add(this.label41);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label41]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.reflectorPosition = global::Gtk.ComboBox.NewText();
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.reflectorPosition.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.reflectorPosition.Name = "combobox43";
		this.reflectorPosition.Active = 0;
		this.hbox7.Add(this.reflectorPosition);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.reflectorPosition]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox8.Add(this.hbox7);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox7]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.GtkAlignment.Add(this.vbox8);
		this.frame3.Add(this.GtkAlignment);
		this.GtkLabel = new global::Gtk.Label();
		this.GtkLabel.Name = "GtkLabel";
		this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Reflector</b>");
		this.GtkLabel.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel;
		this.vbox4.Add(this.frame3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frame3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label();
		this.label13.WidthRequest = 80;
		this.label13.Name = "label13";
		this.label13.Xalign = 0F;
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Types");
		this.hbox9.Add(this.label13);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label13]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.rotorLeftType = global::Gtk.ComboBox.NewText();
		this.rotorLeftType.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.rotorLeftType.AppendText(global::Mono.Unix.Catalog.GetString("II"));
		this.rotorLeftType.AppendText(global::Mono.Unix.Catalog.GetString("III"));
		this.rotorLeftType.AppendText(global::Mono.Unix.Catalog.GetString("IV"));
		this.rotorLeftType.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.rotorLeftType.AppendText(global::Mono.Unix.Catalog.GetString("VI"));
		this.rotorLeftType.AppendText(global::Mono.Unix.Catalog.GetString("VII"));
		this.rotorLeftType.AppendText(global::Mono.Unix.Catalog.GetString("VIII"));
		this.rotorLeftType.WidthRequest = 60;
		this.rotorLeftType.Name = "combobox10";
		this.rotorLeftType.Active = 0;
		this.hbox9.Add(this.rotorLeftType);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.rotorLeftType]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.rotorCenterType = global::Gtk.ComboBox.NewText();
		this.rotorCenterType.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.rotorCenterType.AppendText(global::Mono.Unix.Catalog.GetString("II"));
		this.rotorCenterType.AppendText(global::Mono.Unix.Catalog.GetString("III"));
		this.rotorCenterType.AppendText(global::Mono.Unix.Catalog.GetString("IV"));
		this.rotorCenterType.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.rotorCenterType.AppendText(global::Mono.Unix.Catalog.GetString("VI"));
		this.rotorCenterType.AppendText(global::Mono.Unix.Catalog.GetString("VII"));
		this.rotorCenterType.AppendText(global::Mono.Unix.Catalog.GetString("VIII"));
		this.rotorCenterType.WidthRequest = 60;
		this.rotorCenterType.Name = "combobox11";
		this.rotorCenterType.Active = 1;
		this.hbox9.Add(this.rotorCenterType);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.rotorCenterType]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.rotorRightType = global::Gtk.ComboBox.NewText();
		this.rotorRightType.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.rotorRightType.AppendText(global::Mono.Unix.Catalog.GetString("II"));
		this.rotorRightType.AppendText(global::Mono.Unix.Catalog.GetString("III"));
		this.rotorRightType.AppendText(global::Mono.Unix.Catalog.GetString("IV"));
		this.rotorRightType.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.rotorRightType.AppendText(global::Mono.Unix.Catalog.GetString("VI"));
		this.rotorRightType.AppendText(global::Mono.Unix.Catalog.GetString("VII"));
		this.rotorRightType.AppendText(global::Mono.Unix.Catalog.GetString("VIII"));
		this.rotorRightType.WidthRequest = 60;
		this.rotorRightType.Name = "combobox12";
		this.rotorRightType.Active = 2;
		this.hbox9.Add(this.rotorRightType);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.rotorRightType]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox6.Add(this.hbox9);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label();
		this.label14.WidthRequest = 80;
		this.label14.Name = "label14";
		this.label14.Xalign = 0F;
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Positions");
		this.hbox10.Add(this.label14);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label14]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.rotorLeftPosotion = global::Gtk.ComboBox.NewText();
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.rotorLeftPosotion.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.rotorLeftPosotion.WidthRequest = 60;
		this.rotorLeftPosotion.Name = "combobox13";
		this.rotorLeftPosotion.Active = 0;
		this.hbox10.Add(this.rotorLeftPosotion);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.rotorLeftPosotion]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.rotorCenterPosition = global::Gtk.ComboBox.NewText();
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.rotorCenterPosition.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.rotorCenterPosition.WidthRequest = 60;
		this.rotorCenterPosition.Name = "combobox14";
		this.rotorCenterPosition.Active = 0;
		this.hbox10.Add(this.rotorCenterPosition);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.rotorCenterPosition]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.rotorRightPosition = global::Gtk.ComboBox.NewText();
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.rotorRightPosition.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.rotorRightPosition.WidthRequest = 60;
		this.rotorRightPosition.Name = "combobox15";
		this.rotorRightPosition.Active = 0;
		this.hbox10.Add(this.rotorRightPosition);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.rotorRightPosition]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox6.Add(this.hbox10);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox10]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.GtkAlignment1.Add(this.vbox6);
		this.frame4.Add(this.GtkAlignment1);
		this.GtkLabel1 = new global::Gtk.Label();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Rotors</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel1;
		this.vbox4.Add(this.frame4);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frame4]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.plugboard1 = new global::Gtk.Frame();
		this.plugboard1.Name = "plugboard1";
		this.plugboard1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child plugboard1.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.plugboard_table = new global::Gtk.Table(((uint)(4)), ((uint)(13)), false);
		this.plugboard_table.Name = "plugboard_table";
		this.plugboard_table.RowSpacing = ((uint)(6));
		this.plugboard_table.ColumnSpacing = ((uint)(6));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.A = global::Gtk.ComboBox.NewText();
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.A.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.A.Name = "A";
		this.plugboard_table.Add(this.A);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.A]));
		w23.TopAttach = ((uint)(1));
		w23.BottomAttach = ((uint)(2));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.B = global::Gtk.ComboBox.NewText();
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.B.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.B.Name = "B";
		this.plugboard_table.Add(this.B);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.B]));
		w24.TopAttach = ((uint)(1));
		w24.BottomAttach = ((uint)(2));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.C = global::Gtk.ComboBox.NewText();
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.C.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.C.Name = "C";
		this.plugboard_table.Add(this.C);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.C]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.LeftAttach = ((uint)(2));
		w25.RightAttach = ((uint)(3));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.D = global::Gtk.ComboBox.NewText();
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.D.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.D.Name = "D";
		this.plugboard_table.Add(this.D);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.D]));
		w26.TopAttach = ((uint)(1));
		w26.BottomAttach = ((uint)(2));
		w26.LeftAttach = ((uint)(3));
		w26.RightAttach = ((uint)(4));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.E = global::Gtk.ComboBox.NewText();
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.E.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.E.Name = "E";
		this.plugboard_table.Add(this.E);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.E]));
		w27.TopAttach = ((uint)(1));
		w27.BottomAttach = ((uint)(2));
		w27.LeftAttach = ((uint)(4));
		w27.RightAttach = ((uint)(5));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.F = global::Gtk.ComboBox.NewText();
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.F.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.F.Name = "F";
		this.plugboard_table.Add(this.F);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.F]));
		w28.TopAttach = ((uint)(1));
		w28.BottomAttach = ((uint)(2));
		w28.LeftAttach = ((uint)(5));
		w28.RightAttach = ((uint)(6));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.G = global::Gtk.ComboBox.NewText();
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.G.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.G.Name = "G";
		this.plugboard_table.Add(this.G);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.G]));
		w29.TopAttach = ((uint)(1));
		w29.BottomAttach = ((uint)(2));
		w29.LeftAttach = ((uint)(6));
		w29.RightAttach = ((uint)(7));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.H = global::Gtk.ComboBox.NewText();
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.H.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.H.Name = "H";
		this.plugboard_table.Add(this.H);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.H]));
		w30.TopAttach = ((uint)(1));
		w30.BottomAttach = ((uint)(2));
		w30.LeftAttach = ((uint)(7));
		w30.RightAttach = ((uint)(8));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.I = global::Gtk.ComboBox.NewText();
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.I.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.I.Name = "I";
		this.plugboard_table.Add(this.I);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.I]));
		w31.TopAttach = ((uint)(1));
		w31.BottomAttach = ((uint)(2));
		w31.LeftAttach = ((uint)(8));
		w31.RightAttach = ((uint)(9));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.J = global::Gtk.ComboBox.NewText();
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.J.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.J.Name = "J";
		this.plugboard_table.Add(this.J);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.J]));
		w32.TopAttach = ((uint)(1));
		w32.BottomAttach = ((uint)(2));
		w32.LeftAttach = ((uint)(9));
		w32.RightAttach = ((uint)(10));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.K = global::Gtk.ComboBox.NewText();
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.K.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.K.Name = "K";
		this.plugboard_table.Add(this.K);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.K]));
		w33.TopAttach = ((uint)(1));
		w33.BottomAttach = ((uint)(2));
		w33.LeftAttach = ((uint)(10));
		w33.RightAttach = ((uint)(11));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.L = global::Gtk.ComboBox.NewText();
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.L.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.L.Name = "L";
		this.plugboard_table.Add(this.L);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.L]));
		w34.TopAttach = ((uint)(1));
		w34.BottomAttach = ((uint)(2));
		w34.LeftAttach = ((uint)(11));
		w34.RightAttach = ((uint)(12));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("A");
		this.plugboard_table.Add(this.label15);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label15]));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("B");
		this.plugboard_table.Add(this.label16);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label16]));
		w36.LeftAttach = ((uint)(1));
		w36.RightAttach = ((uint)(2));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("C");
		this.plugboard_table.Add(this.label17);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label17]));
		w37.LeftAttach = ((uint)(2));
		w37.RightAttach = ((uint)(3));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("D");
		this.plugboard_table.Add(this.label18);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label18]));
		w38.LeftAttach = ((uint)(3));
		w38.RightAttach = ((uint)(4));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("E");
		this.plugboard_table.Add(this.label19);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label19]));
		w39.LeftAttach = ((uint)(4));
		w39.RightAttach = ((uint)(5));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("F");
		this.plugboard_table.Add(this.label20);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label20]));
		w40.LeftAttach = ((uint)(5));
		w40.RightAttach = ((uint)(6));
		w40.XOptions = ((global::Gtk.AttachOptions)(4));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("G");
		this.plugboard_table.Add(this.label21);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label21]));
		w41.LeftAttach = ((uint)(6));
		w41.RightAttach = ((uint)(7));
		w41.XOptions = ((global::Gtk.AttachOptions)(4));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("H");
		this.plugboard_table.Add(this.label22);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label22]));
		w42.LeftAttach = ((uint)(7));
		w42.RightAttach = ((uint)(8));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("I");
		this.plugboard_table.Add(this.label23);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label23]));
		w43.LeftAttach = ((uint)(8));
		w43.RightAttach = ((uint)(9));
		w43.XOptions = ((global::Gtk.AttachOptions)(4));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label24 = new global::Gtk.Label();
		this.label24.Name = "label24";
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("J");
		this.plugboard_table.Add(this.label24);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label24]));
		w44.LeftAttach = ((uint)(9));
		w44.RightAttach = ((uint)(10));
		w44.XOptions = ((global::Gtk.AttachOptions)(4));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label25 = new global::Gtk.Label();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("K");
		this.plugboard_table.Add(this.label25);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label25]));
		w45.LeftAttach = ((uint)(10));
		w45.RightAttach = ((uint)(11));
		w45.XOptions = ((global::Gtk.AttachOptions)(4));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label26 = new global::Gtk.Label();
		this.label26.Name = "label26";
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("L");
		this.plugboard_table.Add(this.label26);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label26]));
		w46.LeftAttach = ((uint)(11));
		w46.RightAttach = ((uint)(12));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label27 = new global::Gtk.Label();
		this.label27.Name = "label27";
		this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("M");
		this.plugboard_table.Add(this.label27);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label27]));
		w47.LeftAttach = ((uint)(12));
		w47.RightAttach = ((uint)(13));
		w47.XOptions = ((global::Gtk.AttachOptions)(4));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label28 = new global::Gtk.Label();
		this.label28.Name = "label28";
		this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("N");
		this.plugboard_table.Add(this.label28);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label28]));
		w48.TopAttach = ((uint)(2));
		w48.BottomAttach = ((uint)(3));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label29 = new global::Gtk.Label();
		this.label29.Name = "label29";
		this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("O");
		this.plugboard_table.Add(this.label29);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label29]));
		w49.TopAttach = ((uint)(2));
		w49.BottomAttach = ((uint)(3));
		w49.LeftAttach = ((uint)(1));
		w49.RightAttach = ((uint)(2));
		w49.XOptions = ((global::Gtk.AttachOptions)(4));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label30 = new global::Gtk.Label();
		this.label30.Name = "label30";
		this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("P");
		this.plugboard_table.Add(this.label30);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label30]));
		w50.TopAttach = ((uint)(2));
		w50.BottomAttach = ((uint)(3));
		w50.LeftAttach = ((uint)(2));
		w50.RightAttach = ((uint)(3));
		w50.XOptions = ((global::Gtk.AttachOptions)(4));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label31 = new global::Gtk.Label();
		this.label31.Name = "label31";
		this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Q");
		this.plugboard_table.Add(this.label31);
		global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label31]));
		w51.TopAttach = ((uint)(2));
		w51.BottomAttach = ((uint)(3));
		w51.LeftAttach = ((uint)(3));
		w51.RightAttach = ((uint)(4));
		w51.XOptions = ((global::Gtk.AttachOptions)(4));
		w51.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label32 = new global::Gtk.Label();
		this.label32.Name = "label32";
		this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("R");
		this.plugboard_table.Add(this.label32);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label32]));
		w52.TopAttach = ((uint)(2));
		w52.BottomAttach = ((uint)(3));
		w52.LeftAttach = ((uint)(4));
		w52.RightAttach = ((uint)(5));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label33 = new global::Gtk.Label();
		this.label33.Name = "label33";
		this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("S");
		this.plugboard_table.Add(this.label33);
		global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label33]));
		w53.TopAttach = ((uint)(2));
		w53.BottomAttach = ((uint)(3));
		w53.LeftAttach = ((uint)(5));
		w53.RightAttach = ((uint)(6));
		w53.XOptions = ((global::Gtk.AttachOptions)(4));
		w53.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label34 = new global::Gtk.Label();
		this.label34.Name = "label34";
		this.label34.LabelProp = global::Mono.Unix.Catalog.GetString("T");
		this.plugboard_table.Add(this.label34);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label34]));
		w54.TopAttach = ((uint)(2));
		w54.BottomAttach = ((uint)(3));
		w54.LeftAttach = ((uint)(6));
		w54.RightAttach = ((uint)(7));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label35 = new global::Gtk.Label();
		this.label35.Name = "label35";
		this.label35.LabelProp = global::Mono.Unix.Catalog.GetString("U");
		this.plugboard_table.Add(this.label35);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label35]));
		w55.TopAttach = ((uint)(2));
		w55.BottomAttach = ((uint)(3));
		w55.LeftAttach = ((uint)(7));
		w55.RightAttach = ((uint)(8));
		w55.XOptions = ((global::Gtk.AttachOptions)(4));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label36 = new global::Gtk.Label();
		this.label36.Name = "label36";
		this.label36.LabelProp = global::Mono.Unix.Catalog.GetString("V");
		this.plugboard_table.Add(this.label36);
		global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label36]));
		w56.TopAttach = ((uint)(2));
		w56.BottomAttach = ((uint)(3));
		w56.LeftAttach = ((uint)(8));
		w56.RightAttach = ((uint)(9));
		w56.XOptions = ((global::Gtk.AttachOptions)(4));
		w56.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label37 = new global::Gtk.Label();
		this.label37.Name = "label37";
		this.label37.LabelProp = global::Mono.Unix.Catalog.GetString("W");
		this.plugboard_table.Add(this.label37);
		global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label37]));
		w57.TopAttach = ((uint)(2));
		w57.BottomAttach = ((uint)(3));
		w57.LeftAttach = ((uint)(9));
		w57.RightAttach = ((uint)(10));
		w57.XOptions = ((global::Gtk.AttachOptions)(4));
		w57.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label38 = new global::Gtk.Label();
		this.label38.Name = "label38";
		this.label38.LabelProp = global::Mono.Unix.Catalog.GetString("X");
		this.plugboard_table.Add(this.label38);
		global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label38]));
		w58.TopAttach = ((uint)(2));
		w58.BottomAttach = ((uint)(3));
		w58.LeftAttach = ((uint)(10));
		w58.RightAttach = ((uint)(11));
		w58.XOptions = ((global::Gtk.AttachOptions)(4));
		w58.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label39 = new global::Gtk.Label();
		this.label39.Name = "label39";
		this.label39.LabelProp = global::Mono.Unix.Catalog.GetString("Y");
		this.plugboard_table.Add(this.label39);
		global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label39]));
		w59.TopAttach = ((uint)(2));
		w59.BottomAttach = ((uint)(3));
		w59.LeftAttach = ((uint)(11));
		w59.RightAttach = ((uint)(12));
		w59.XOptions = ((global::Gtk.AttachOptions)(4));
		w59.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.label40 = new global::Gtk.Label();
		this.label40.Name = "label40";
		this.label40.LabelProp = global::Mono.Unix.Catalog.GetString("Z");
		this.plugboard_table.Add(this.label40);
		global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.label40]));
		w60.TopAttach = ((uint)(2));
		w60.BottomAttach = ((uint)(3));
		w60.LeftAttach = ((uint)(12));
		w60.RightAttach = ((uint)(13));
		w60.XOptions = ((global::Gtk.AttachOptions)(4));
		w60.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.M = global::Gtk.ComboBox.NewText();
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.M.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.M.Name = "M";
		this.plugboard_table.Add(this.M);
		global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.M]));
		w61.TopAttach = ((uint)(1));
		w61.BottomAttach = ((uint)(2));
		w61.LeftAttach = ((uint)(12));
		w61.RightAttach = ((uint)(13));
		w61.XOptions = ((global::Gtk.AttachOptions)(4));
		w61.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.N = global::Gtk.ComboBox.NewText();
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.N.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.N.Name = "N";
		this.plugboard_table.Add(this.N);
		global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.N]));
		w62.TopAttach = ((uint)(3));
		w62.BottomAttach = ((uint)(4));
		w62.XOptions = ((global::Gtk.AttachOptions)(4));
		w62.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.O = global::Gtk.ComboBox.NewText();
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.O.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.O.Name = "O";
		this.plugboard_table.Add(this.O);
		global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.O]));
		w63.TopAttach = ((uint)(3));
		w63.BottomAttach = ((uint)(4));
		w63.LeftAttach = ((uint)(1));
		w63.RightAttach = ((uint)(2));
		w63.XOptions = ((global::Gtk.AttachOptions)(4));
		w63.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.P = global::Gtk.ComboBox.NewText();
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.P.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.P.Name = "P";
		this.plugboard_table.Add(this.P);
		global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.P]));
		w64.TopAttach = ((uint)(3));
		w64.BottomAttach = ((uint)(4));
		w64.LeftAttach = ((uint)(2));
		w64.RightAttach = ((uint)(3));
		w64.XOptions = ((global::Gtk.AttachOptions)(4));
		w64.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.Q = global::Gtk.ComboBox.NewText();
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.Q.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.Q.Name = "Q";
		this.plugboard_table.Add(this.Q);
		global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.Q]));
		w65.TopAttach = ((uint)(3));
		w65.BottomAttach = ((uint)(4));
		w65.LeftAttach = ((uint)(3));
		w65.RightAttach = ((uint)(4));
		w65.XOptions = ((global::Gtk.AttachOptions)(4));
		w65.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.R = global::Gtk.ComboBox.NewText();
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.R.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.R.Name = "R";
		this.plugboard_table.Add(this.R);
		global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.R]));
		w66.TopAttach = ((uint)(3));
		w66.BottomAttach = ((uint)(4));
		w66.LeftAttach = ((uint)(4));
		w66.RightAttach = ((uint)(5));
		w66.XOptions = ((global::Gtk.AttachOptions)(4));
		w66.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.S = global::Gtk.ComboBox.NewText();
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.S.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.S.Name = "S";
		this.plugboard_table.Add(this.S);
		global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.S]));
		w67.TopAttach = ((uint)(3));
		w67.BottomAttach = ((uint)(4));
		w67.LeftAttach = ((uint)(5));
		w67.RightAttach = ((uint)(6));
		w67.XOptions = ((global::Gtk.AttachOptions)(4));
		w67.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.T = global::Gtk.ComboBox.NewText();
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.T.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.T.Name = "T";
		this.plugboard_table.Add(this.T);
		global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.T]));
		w68.TopAttach = ((uint)(3));
		w68.BottomAttach = ((uint)(4));
		w68.LeftAttach = ((uint)(6));
		w68.RightAttach = ((uint)(7));
		w68.XOptions = ((global::Gtk.AttachOptions)(4));
		w68.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.U = global::Gtk.ComboBox.NewText();
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.U.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.U.Name = "U";
		this.plugboard_table.Add(this.U);
		global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.U]));
		w69.TopAttach = ((uint)(3));
		w69.BottomAttach = ((uint)(4));
		w69.LeftAttach = ((uint)(7));
		w69.RightAttach = ((uint)(8));
		w69.XOptions = ((global::Gtk.AttachOptions)(4));
		w69.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.V = global::Gtk.ComboBox.NewText();
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.V.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.V.Name = "V";
		this.plugboard_table.Add(this.V);
		global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.V]));
		w70.TopAttach = ((uint)(3));
		w70.BottomAttach = ((uint)(4));
		w70.LeftAttach = ((uint)(8));
		w70.RightAttach = ((uint)(9));
		w70.XOptions = ((global::Gtk.AttachOptions)(4));
		w70.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.W = global::Gtk.ComboBox.NewText();
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.W.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.W.Name = "W";
		this.plugboard_table.Add(this.W);
		global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.W]));
		w71.TopAttach = ((uint)(3));
		w71.BottomAttach = ((uint)(4));
		w71.LeftAttach = ((uint)(9));
		w71.RightAttach = ((uint)(10));
		w71.XOptions = ((global::Gtk.AttachOptions)(4));
		w71.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.X = global::Gtk.ComboBox.NewText();
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.X.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.X.Name = "X";
		this.plugboard_table.Add(this.X);
		global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.X]));
		w72.TopAttach = ((uint)(3));
		w72.BottomAttach = ((uint)(4));
		w72.LeftAttach = ((uint)(10));
		w72.RightAttach = ((uint)(11));
		w72.XOptions = ((global::Gtk.AttachOptions)(4));
		w72.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.Y = global::Gtk.ComboBox.NewText();
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.Y.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.Y.Name = "Y";
		this.plugboard_table.Add(this.Y);
		global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.Y]));
		w73.TopAttach = ((uint)(3));
		w73.BottomAttach = ((uint)(4));
		w73.LeftAttach = ((uint)(11));
		w73.RightAttach = ((uint)(12));
		w73.XOptions = ((global::Gtk.AttachOptions)(4));
		w73.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child plugboard_table.Gtk.Table+TableChild
		this.Z = global::Gtk.ComboBox.NewText();
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("A"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("B"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("C"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("D"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("E"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("F"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("G"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("H"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("I"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("J"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("K"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("L"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("M"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("N"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("O"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("P"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("Q"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("R"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("S"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("T"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("U"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("V"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("W"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("X"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("Y"));
		this.Z.AppendText(global::Mono.Unix.Catalog.GetString("Z"));
		this.Z.Name = "Z";
		this.plugboard_table.Add(this.Z);
		global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.plugboard_table[this.Z]));
		w74.TopAttach = ((uint)(3));
		w74.BottomAttach = ((uint)(4));
		w74.LeftAttach = ((uint)(12));
		w74.RightAttach = ((uint)(13));
		w74.XOptions = ((global::Gtk.AttachOptions)(4));
		w74.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment2.Add(this.plugboard_table);
		this.plugboard1.Add(this.GtkAlignment2);
		this.GtkLabel2 = new global::Gtk.Label();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Plugboard</b>");
		this.GtkLabel2.UseMarkup = true;
		this.plugboard1.LabelWidget = this.GtkLabel2;
		this.vbox4.Add(this.plugboard1);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.plugboard1]));
		w77.Position = 2;
		w77.Expand = false;
		w77.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.frame8 = new global::Gtk.Frame();
		this.frame8.Name = "frame8";
		this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame8.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.inputText = new global::Gtk.TextView();
		this.inputText.CanFocus = true;
		this.inputText.Name = "text_input";
		this.GtkScrolledWindow.Add(this.inputText);
		this.hbox11.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.GtkScrolledWindow]));
		w79.Position = 0;
		// Container child hbox11.Gtk.Box+BoxChild
		this.decryptedMessage = new global::Gtk.ScrolledWindow();
		this.decryptedMessage.CanFocus = true;
		this.decryptedMessage.Name = "decryptedMessage";
		this.decryptedMessage.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child decryptedMessage.Gtk.Container+ContainerChild
		this.outputText = new global::Gtk.TextView();
		this.outputText.CanFocus = true;
		this.outputText.Name = "text_output";
		this.outputText.Editable = false;
		this.decryptedMessage.Add(this.outputText);
		this.hbox11.Add(this.decryptedMessage);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.decryptedMessage]));
		w81.Position = 1;
		this.vbox7.Add(this.hbox11);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox11]));
		w82.Position = 0;
		// Container child vbox7.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Encrypt/Decrypt");
		this.vbox7.Add(this.button3);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.button3]));
		w83.Position = 1;
		w83.Expand = false;
		w83.Fill = false;
		this.GtkAlignment3.Add(this.vbox7);
		this.frame8.Add(this.GtkAlignment3);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Text</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame8.LabelWidget = this.GtkLabel4;
		this.vbox4.Add(this.frame8);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frame8]));
		w86.Position = 3;
		this.Add(this.vbox4);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 712;
		this.DefaultHeight = 459;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Z.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.Y.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.X.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.W.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.V.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.U.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.T.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.S.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.R.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.Q.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.P.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.O.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.N.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.M.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.L.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.K.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.J.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.I.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.H.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.G.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.F.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.E.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.D.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.C.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.B.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.A.Changed += new global::System.EventHandler(this.SelectPlugboard);
		this.button3.Clicked += new global::System.EventHandler(this.ButtonClick);
	}
}
